// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjKXtBn16LEvxJC9Uw-d0ip6bBD4OpXFM',
    appId: '1:907339903934:web:9f270785e3366df855bfef',
    messagingSenderId: '907339903934',
    projectId: 'biblescroll-93249',
    authDomain: 'biblescroll-93249.firebaseapp.com',
    storageBucket: 'biblescroll-93249.firebasestorage.app',
    measurementId: 'G-PYZMXTLJ5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtIlqcsxGAh4Wsb3bqSHzn-sY9c8p8pc8',
    appId: '1:907339903934:android:bd33e862d55baed855bfef',
    messagingSenderId: '907339903934',
    projectId: 'biblescroll-93249',
    storageBucket: 'biblescroll-93249.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyFE1dWugMstn08s9bYu5W1zvg_X3SEK4',
    appId: '1:907339903934:ios:c4ac077e449dc50855bfef',
    messagingSenderId: '907339903934',
    projectId: 'biblescroll-93249',
    storageBucket: 'biblescroll-93249.firebasestorage.app',
    iosClientId: '907339903934-k0acfm3vm2ipuui3b9vnn88k6stq6jp9.apps.googleusercontent.com',
    iosBundleId: 'app.biblescroll.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyFE1dWugMstn08s9bYu5W1zvg_X3SEK4',
    appId: '1:907339903934:ios:c4ac077e449dc50855bfef',
    messagingSenderId: '907339903934',
    projectId: 'biblescroll-93249',
    storageBucket: 'biblescroll-93249.firebasestorage.app',
    iosClientId: '907339903934-k0acfm3vm2ipuui3b9vnn88k6stq6jp9.apps.googleusercontent.com',
    iosBundleId: 'app.biblescroll.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjKXtBn16LEvxJC9Uw-d0ip6bBD4OpXFM',
    appId: '1:907339903934:web:7cdedf3362b89b2d55bfef',
    messagingSenderId: '907339903934',
    projectId: 'biblescroll-93249',
    authDomain: 'biblescroll-93249.firebaseapp.com',
    storageBucket: 'biblescroll-93249.firebasestorage.app',
    measurementId: 'G-KNMZW9KD9L',
  );
}
